#pragma once
#define CHAT_FLAG_UNKNOWN1 0x1
#define CHAT_FLAG_ORANGE 0x2
#define CHAT_FLAG_WHITE 0x4
#define CHAT_FLAG_UNKNOWN2 0x8
#define CHAT_FLAG_GREEN 0x10
#define CHAT_FLAG_YELLOW 0x20
#define CHAT_FLAG_GOLD 0x40
#define CHAT_FLAG_UNKNOWN3 0x80
#define CHAT_FLAG_TURQUOISE 0x100   